<!DOCTYPE html>
<html lang="zh-CN">
        
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>异常处理.Ve语言</title>
</head>

<body>
    <!-- inject:header:html -->
    <header>

    </header>
    <!-- endinject -->
    <!-- inject:message:html -->
    <div class="message-banner">

    </div>
    <!-- endinject -->
    <div class="container">
        <div class="navs">
            
    <ul>
        
           <li class="panel">
                <a>辅导教程</a>
                <ul>
                <li class="item"><a href="/typescript-in-5-minutes.html" >5分钟上手TypeScript</a></li>
                </ul>
           </li>
           

           <li class="panel">
                <a>手册指南</a>
                <ul>
                <li class="item"><a href="/variable-declarations.html" >变量声明</a></li>
<li class="item"><a href="/generics.html" >泛型</a></li>
<li class="item"><a href="/functions.html" >函数</a></li>
<li class="item"><a href="/basic-types.html" >基础类型</a></li>
<li class="item"><a href="/interfaces.html" >接口</a></li>
<li class="item"><a href="/classes.html" >类</a></li>
<li class="item"><a href="/namespaces.html" >命名空间</a></li>
<li class="item"><a href="/modules.html" >模块</a></li>
<li class="item"><a href="/exceptions.html" class="active">异常处理</a></li>
<li class="item"><a href="/operators.html" >运算符</a></li>
                </ul>
           </li>
           
    </ul>
    
        </div>
        <div class="content">
            <h1 id="异常处理">异常处理</h1>
<h2 id="介绍">介绍</h2>
<p>异常是程序中的一些错误，但并不是所有的错误都是异常，并且错误有时候是可以避免的。</p>
<p>比如说，你用print(11/0)，那么你是因为你用0做了除数，会抛出 Ve.DivideByZeroException 的异常。</p>
<h2 id="异常类">异常类</h2>
<p>下面的表中列出了Ve 的异常类。<br />
|异常类|描述|<br />
|-|-|<br />
|Ve.IndexOutOfRangeException|处理当方法指向超出范围的数组索引时生成的错误。<br />
|Ve.ArrayTypeMismatchException|处理当数组类型不匹配时生成的错误。<br />
|Ve.NullReferenceException|处理当依从一个空对象时生成的错误。<br />
|Ve.DivideByZeroException|处理当除以零时生成的错误。<br />
|Ve.InvalidCastException|处理在类型转换期间生成的错误。</p>
<h2 id="捕获异常">捕获异常</h2>
<p>语法:</p>
<pre><code>try{
   // 引起异常的语句
}
catch(ExceptionName e1){
   // 错误处理代码
}
...
catch(ExceptionName e1){
   // 错误处理代码
}
finally{
   // 要执行的语句
}</code></pre>
<p>try语句包含了由一个或者多个语句组成的try块, 和至少一个catch子句或者一个finally子句的其中一个，或者两个兼有， 下面是三种形式的try声明：</p>
<ol>
<li>try…catch</li>
<li>try…finally</li>
<li>try…catch…finally<br />
catch子句包含try块中抛出异常时要执行的语句。也就是，你想让try语句中的内容成功， 如果没成功，你想控制接下来发生的事情，这时你可以在catch语句中实现。 如果在try块中有任何一个语句（或者从try块中调用的函数）抛出异常，控制立即转向catch子句。如果在try块中没有异常抛出，会跳过catch子句。</li>
</ol>
<p>finally子句在try块和catch块之后执行但是在下一个try声明之前执行。无论是否有异常抛出或捕获它总是执行。</p>
<p>你可以嵌套一个或者更多的try语句。如果内部的try语句没有catch子句，那么将会进入包裹它的try语句的catch子句。</p>
        </div>
    </div>
    <!-- inject:footer:html -->
    <footer style="position: relative; z-index: 100;">

    </footer>
    <!-- endinject -->
</body>

</html>